name: Hyperliquid Data Snapshot

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  fetch-data:
    runs-on: ubuntu-latest # Actions run on Linux servers by default
    permissions:
      contents: write # Need permission to write back to the repo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Or your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hyperliquid-python-sdk

      - name: Run snapshot script
        run: python snapshot_collector.py # Your modified Python script

      - name: Commit data file
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action-bot@github.com'
          git add snapshot.json # Add the file created by your script
          # Commit only if there are changes
          git diff --staged --quiet || git commit -m "Update data snapshot"
          git push
